//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DojoTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class badge
    {
        public badge()
        {
            this.badgeSteps = new HashSet<badgeStep>();
        }
    
        public int badgeId { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public int badgeStepId { get; set; }
        public bool active { get; set; }
    
        public virtual ICollection<badgeStep> badgeSteps { get; set; }
    }
}
