//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DojoTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class badgeStep
    {
        public badgeStep()
        {
            this.badgeStepsAchieveds = new HashSet<badgeStepsAchieved>();
        }
    
        public int badgeStepId { get; set; }
        public int badgeId { get; set; }
        public int stepNo { get; set; }
        public string stepDesc { get; set; }
        public bool active { get; set; }
    
        public virtual badge badge { get; set; }
        public virtual ICollection<badgeStepsAchieved> badgeStepsAchieveds { get; set; }
    }
}
