//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DojoTest
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DojoContext : DbContext
    {
        public DojoContext()
            : base("name=DojoContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<badge> badges { get; set; }
        public virtual DbSet<badgeStep> badgeSteps { get; set; }
        public virtual DbSet<badgeStepsAchieved> badgeStepsAchieveds { get; set; }
        public virtual DbSet<dojoClass> dojoClasses { get; set; }
        public virtual DbSet<mentor> mentors { get; set; }
        public virtual DbSet<mentorAttendance> mentorAttendances { get; set; }
        public virtual DbSet<ninja> ninjas { get; set; }
        public virtual DbSet<ninjaAttendance> ninjaAttendances { get; set; }
    }
}
